name: MuggleTalent
services:
  db:
    image: postgres:16.9
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: muggletalent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/pgsql/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - postgres
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
      - -c
      - listen_addresses=*
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d muggletalent"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
