name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/debian/MuggleTalent
            sudo git pull origin main
            docker compose exec app php artisan config:clear
            docker compose exec app php artisan cache:clear
            docker compose exec app php artisan route:clear
            docker compose exec app php artisan view:clear
            docker compose exec app php artisan migrate --force
            docker compose down
            docker compose up -d --build
